.TH "ntw::Communication" 3 "Thu Jan 11 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ntw::Communication
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename TType > void \fBadd_param\fP (TType param)"
.br
.ti -1c
.RI "std::vector< std::string > \fBdeserialize\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "NetworkType \fBtype\fP {NetworkType::None}"
.br
.ti -1c
.RI "std::array< char, MAX_SIZE > \fBargs\fP {}"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
