.TH "rclient::Client::ClientException" 3 "Sun Jan 14 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rclient::Client::ClientException
.SH SYNOPSIS
.br
.PP
.PP
Inherits std::exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClientException\fP (std::string &&perror_msg)"
.br
.ti -1c
.RI "\fBClientException\fP (\fBClientException\fP const &to_copy)=default"
.br
.ti -1c
.RI "\fBClientException\fP (\fBClientException\fP &&to_move)=default"
.br
.ti -1c
.RI "\fBClientException\fP & \fBoperator=\fP (\fBClientException\fP const &to_copy)=default"
.br
.ti -1c
.RI "\fBClientException\fP & \fBoperator=\fP (\fBClientException\fP &&to_move)=default"
.br
.ti -1c
.RI "const char * \fBwhat\fP () const noexcept override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
