.TH "rclient::ArgsConfig" 3 "Sun Jan 14 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rclient::ArgsConfig \- Parse args and return informations\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ArgsConfig\&.hh>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArgsException\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArgsConfig\fP (\fBArgsConfig\fP const &to_copy)=default"
.br
.ti -1c
.RI "\fBArgsConfig\fP (\fBArgsConfig\fP &&to_move)=default"
.br
.ti -1c
.RI "\fBArgsConfig\fP & \fBoperator=\fP (\fBArgsConfig\fP const &to_copy)=default"
.br
.ti -1c
.RI "\fBArgsConfig\fP & \fBoperator=\fP (\fBArgsConfig\fP &&to_move)=default"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBArguments\fP \fBparse_args\fP (int argc, std::span< const char * > argv)"
.br
.RI "Go through argv elements given in main and get infos\&. "
.in -1c
.SH "Detailed Description"
.PP 
Parse args and return informations\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBrclient::Arguments\fP rclient::ArgsConfig::parse_args (int argc, std::span< const char * > argv)\fC [static]\fP"

.PP
Go through argv elements given in main and get infos\&. 
.PP
\fBParameters\fP
.RS 4
\fIargc\fP - number of elements 
.br
\fIargv\fP - span<const char *> - safer way to handle argv 
.RE
.PP
\fBReturns\fP
.RS 4
- \fBArguments\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
