.TH "rclient::ArgsConfig" 3 "Tue Jan 9 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rclient::ArgsConfig
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArgsException\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArgsConfig\fP (\fBArgsConfig\fP const &to_copy)=default"
.br
.ti -1c
.RI "\fBArgsConfig\fP (\fBArgsConfig\fP &&to_move)=default"
.br
.ti -1c
.RI "\fBArgsConfig\fP & \fBoperator=\fP (\fBArgsConfig\fP const &to_copy)=default"
.br
.ti -1c
.RI "\fBArgsConfig\fP & \fBoperator=\fP (\fBArgsConfig\fP &&to_move)=default"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBArguments\fP \fBparse_args\fP (int argc, std::span< const char * > argv)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
