.TH "rclient::BackgroundSpecifier" 3 "Sun Jan 14 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rclient::BackgroundSpecifier \- Utils for background, to apply transform and sprite components\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BackgroundManager\&.hh>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBrtype::TransformComponent\fP \fBtransform\fP"
.br
.ti -1c
.RI "\fBrtype::SpriteComponent\fP \fBsprite\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Utils for background, to apply transform and sprite components\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
