.TH "rserver::config::Level" 3 "Thu Jan 11 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rserver::config::Level
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBtitle\fP"
.br
.ti -1c
.RI "std::string \fBbackground\fP"
.br
.ti -1c
.RI "std::string \fBmusic\fP"
.br
.ti -1c
.RI "double \fBtime\fP"
.br
.ti -1c
.RI "std::vector< \fBWave\fP > \fBwaves\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
