.TH "rserver::PlayersManager::PlayersException" 3 "Tue Jan 9 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rserver::PlayersManager::PlayersException
.SH SYNOPSIS
.br
.PP
.PP
Inherits std::exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlayersException\fP (std::string p_error=PM_ERROR\&.data())"
.br
.ti -1c
.RI "\fBPlayersException\fP (\fBPlayersException\fP const &to_copy)=default"
.br
.ti -1c
.RI "\fBPlayersException\fP (\fBPlayersException\fP &&to_move)=default"
.br
.ti -1c
.RI "\fBPlayersException\fP & \fBoperator=\fP (\fBPlayersException\fP const &to_copy)=default"
.br
.ti -1c
.RI "\fBPlayersException\fP & \fBoperator=\fP (\fBPlayersException\fP &&to_move)=default"
.br
.ti -1c
.RI "const char * \fBwhat\fP () const noexcept override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
