.TH "rserver::game::solo::SoloGame" 3 "Fri Jan 12 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rserver::game::solo::SoloGame
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSoloGame\fP (asio::ip::udp::socket &psocket, asio::ip::udp::endpoint &pendpoint)"
.br
.ti -1c
.RI "\fBSoloGame\fP (\fBSoloGame\fP const &to_copy)=delete"
.br
.ti -1c
.RI "\fBSoloGame\fP (\fBSoloGame\fP &&to_move)"
.br
.ti -1c
.RI "\fBSoloGame\fP & \fBoperator=\fP (\fBSoloGame\fP const &to_copy)=delete"
.br
.ti -1c
.RI "\fBSoloGame\fP & \fBoperator=\fP (\fBSoloGame\fP &&to_move)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
