.TH "rserver::ArgsParser" 3 "Fri Jan 12 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rserver::ArgsParser
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArgsException\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArgsParser\fP (\fBArgsParser\fP const &to_copy)=delete"
.br
.ti -1c
.RI "\fBArgsParser\fP (\fBArgsParser\fP &&to_move)=delete"
.br
.ti -1c
.RI "\fBArgsParser\fP & \fBoperator=\fP (\fBArgsParser\fP const &to_copy)=delete"
.br
.ti -1c
.RI "\fBArgsParser\fP & \fBoperator=\fP (\fBArgsParser\fP &&to_move)=delete"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBInfos\fP \fBget_args\fP (int argc, std::span< char const * > argv)"
.br
.RI "Static method to parse args given in agruments\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBrserver::Infos\fP rserver::ArgsParser::get_args (int argc, std::span< char const * > argv)\fC [static]\fP"

.PP
Static method to parse args given in agruments\&. 
.PP
\fBParameters\fP
.RS 4
\fIargc\fP - int 
.br
\fIargv\fP - span<const char *> 
.RE
.PP
\fBReturns\fP
.RS 4
\fBInfos\fP 
.RE
.PP
\fBExceptions\fP
.RS 4
\fI\fBArgsException\fP\fP on error 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
