.TH "rserver::ServerEntityFactory" 3 "Sun Jan 14 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rserver::ServerEntityFactory \- To create entities and register them with the ECS They load the entities through a \&.json file containing all infos of the entities\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ServerEntityFactory\&.hh>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFactoryException\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBServerEntityFactory\fP (const \fBServerEntityFactory\fP &factory)=default"
.br
.ti -1c
.RI "\fBServerEntityFactory\fP (\fBServerEntityFactory\fP &&factory)=default"
.br
.ti -1c
.RI "\fBServerEntityFactory\fP & \fBoperator=\fP (const \fBServerEntityFactory\fP &factory)=default"
.br
.ti -1c
.RI "\fBServerEntityFactory\fP & \fBoperator=\fP (\fBServerEntityFactory\fP &&factory)=default"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static size_t \fBcreate\fP (const std::string &type, \fBrtype::ECSManager\fP &ecs_manager)"
.br
.RI "Create a new entity and register it on the ECS\&. "
.in -1c
.SH "Detailed Description"
.PP 
To create entities and register them with the ECS They load the entities through a \&.json file containing all infos of the entities\&. 
.SH "Member Function Documentation"
.PP 
.SS "size_t rserver::ServerEntityFactory::create (const std::string & type, \fBrtype::ECSManager\fP & ecs_manager)\fC [static]\fP"

.PP
Create a new entity and register it on the ECS\&. 
.PP
\fBParameters\fP
.RS 4
\fItype\fP - string - typename of the entity 
.br
\fIecs_manager\fP - ECSManager 
.RE
.PP
\fBReturns\fP
.RS 4
size_t - id of the new entity 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
