.TH "rserver::LevelManager" 3 "Fri Jan 12 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rserver::LevelManager
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLevelManager\fP (\fBLevelManager\fP const &to_copy)=delete"
.br
.ti -1c
.RI "\fBLevelManager\fP (\fBLevelManager\fP &&to_move)=default"
.br
.ti -1c
.RI "\fBLevelManager\fP & \fBoperator=\fP (\fBLevelManager\fP const &to_copy)=delete"
.br
.ti -1c
.RI "\fBLevelManager\fP & \fBoperator=\fP (\fBLevelManager\fP &&to_move)=delete"
.br
.ti -1c
.RI "void \fBupdate\fP (\fBrtype::ECSManager\fP &ecs_manager)"
.br
.ti -1c
.RI "void \fBmanage_wave\fP (\fBconfig::Level\fP &level, \fBrtype::ECSManager\fP &ecs_manager)"
.br
.ti -1c
.RI "bool \fBhas_enough_level\fP ()"
.br
.ti -1c
.RI "bool \fBis_level_finished\fP ()"
.br
.ti -1c
.RI "void \fBchange_level\fP ()"
.br
.ti -1c
.RI "std::string \fBget_current_music\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
