.TH "rserver::Vector2f" 3 "Mon Jan 8 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rserver::Vector2f
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBpos_x\fP {0\&.0}"
.br
.ti -1c
.RI "float \fBpos_y\fP {0\&.0}"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
