.TH "rserver::config::ConfigsFile::ConfigsException" 3 "Thu Jan 11 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rserver::config::ConfigsFile::ConfigsException
.SH SYNOPSIS
.br
.PP
.PP
Inherits std::exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConfigsException\fP (std::string perror='Error')"
.br
.ti -1c
.RI "\fBConfigsException\fP (\fBConfigsException\fP const &to_copy)=default"
.br
.ti -1c
.RI "\fBConfigsException\fP (\fBConfigsException\fP &&to_move)=default"
.br
.ti -1c
.RI "\fBConfigsException\fP & \fBoperator=\fP (\fBConfigsException\fP const &to_copy)=default"
.br
.ti -1c
.RI "\fBConfigsException\fP & \fBoperator=\fP (\fBConfigsException\fP &&to_move)=default"
.br
.ti -1c
.RI "const char * \fBwhat\fP () const noexcept override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
