.TH "rserver::config::ConfigsFile" 3 "Fri Jan 12 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rserver::config::ConfigsFile
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConfigsException\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConfigsFile\fP (\fBConfigsFile\fP const &to_copy)=default"
.br
.ti -1c
.RI "\fBConfigsFile\fP (\fBConfigsFile\fP &&to_move)=default"
.br
.ti -1c
.RI "\fBConfigsFile\fP & \fBoperator=\fP (\fBConfigsFile\fP const &to_copy)=default"
.br
.ti -1c
.RI "\fBConfigsFile\fP & \fBoperator=\fP (\fBConfigsFile\fP &&to_move)=default"
.br
.ti -1c
.RI "std::vector< \fBLevel\fP > \fBdo_parse\fP ()"
.br
.RI "Method called by parse, to open and parse json file with nlohmann::json\&. "
.ti -1c
.RI "void \fBadd_enemies\fP (const njson &enemies)"
.br
.RI "Add enemies to level\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::vector< \fBLevel\fP > \fBparse\fP ()"
.br
.RI "static method to parse LEVEL_FOLDER file "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void rserver::config::ConfigsFile::add_enemies (const njson & enemies)"

.PP
Add enemies to level\&. 
.PP
\fBParameters\fP
.RS 4
\fIenemies\fP - njson 
.RE
.PP

.SS "std::vector< \fBrserver::config::Level\fP > rserver::config::ConfigsFile::do_parse ()"

.PP
Method called by parse, to open and parse json file with nlohmann::json\&. 
.PP
\fBReturns\fP
.RS 4
vector<Level> 
.RE
.PP
\fBExceptions\fP
.RS 4
\fI\fBConfigsException\fP\fP if something goes wrong 
.RE
.PP

.SS "std::vector< \fBrserver::config::Level\fP > rserver::config::ConfigsFile::parse ()\fC [static]\fP"

.PP
static method to parse LEVEL_FOLDER file 
.PP
\fBExceptions\fP
.RS 4
\fI\fBConfigsException\fP\fP if something goes wrong 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
