.TH "rserver::config::Wave" 3 "Thu Jan 11 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rserver::config::Wave
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBtime\fP"
.br
.ti -1c
.RI "bool \fBis_done\fP {false}"
.br
.ti -1c
.RI "std::vector< std::string > \fBenemies\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
