.TH "rserver::ArgsParser" 3 "Wed Jan 10 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rserver::ArgsParser
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArgsException\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArgsParser\fP (\fBArgsParser\fP const &to_copy)=delete"
.br
.ti -1c
.RI "\fBArgsParser\fP (\fBArgsParser\fP &&to_move)=delete"
.br
.ti -1c
.RI "\fBArgsParser\fP & \fBoperator=\fP (\fBArgsParser\fP const &to_copy)=delete"
.br
.ti -1c
.RI "\fBArgsParser\fP & \fBoperator=\fP (\fBArgsParser\fP &&to_move)=delete"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBInfos\fP \fBget_args\fP (int argc, std::span< char const * > argv)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
