.TH "rserver::game::Room::RoomException" 3 "Sat Jan 13 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rserver::game::Room::RoomException
.SH SYNOPSIS
.br
.PP
.PP
Inherits std::exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRoomException\fP (std::string &&perror='Error')"
.br
.ti -1c
.RI "\fBRoomException\fP (\fBRoomException\fP const &to_copy)=default"
.br
.ti -1c
.RI "\fBRoomException\fP (\fBRoomException\fP &&to_move)=default"
.br
.ti -1c
.RI "\fBRoomException\fP & \fBoperator=\fP (\fBRoomException\fP const &to_copy)=default"
.br
.ti -1c
.RI "\fBRoomException\fP & \fBoperator=\fP (\fBRoomException\fP &&to_move)=default"
.br
.ti -1c
.RI "const char * \fBwhat\fP () const noexcept override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
