.TH "rtype::IComp" 3 "Sun Jan 14 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rtype::IComp
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIComp\fP (\fBIComp\fP const &to_copy)=default"
.br
.ti -1c
.RI "\fBIComp\fP (\fBIComp\fP &&to_move)=default"
.br
.ti -1c
.RI "\fBIComp\fP & \fBoperator=\fP (\fBIComp\fP const &to_copy)=default"
.br
.ti -1c
.RI "\fBIComp\fP & \fBoperator=\fP (\fBIComp\fP &&to_move)=default"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
