.TH "rtype::Entity" 3 "Sat Jan 13 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rtype::Entity
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEntity\fP (std::size_t &&index)"
.br
.ti -1c
.RI "\fBEntity\fP (const \fBEntity\fP &)=default"
.br
.ti -1c
.RI "\fBEntity\fP (\fBEntity\fP &&)=default"
.br
.ti -1c
.RI "\fBEntity\fP & \fBoperator=\fP (const \fBEntity\fP &)=default"
.br
.ti -1c
.RI "\fBEntity\fP & \fBoperator=\fP (\fBEntity\fP &&)=default"
.br
.ti -1c
.RI "\fBoperator std::size_t\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
