.TH "rtype::InputManager" 3 "Sun Jan 14 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rtype::InputManager
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInputManager\fP (const \fBInputManager\fP &)=default"
.br
.ti -1c
.RI "\fBInputManager\fP (\fBInputManager\fP &&)=default"
.br
.ti -1c
.RI "\fBInputManager\fP & \fBoperator=\fP (const \fBInputManager\fP &)=default"
.br
.ti -1c
.RI "\fBInputManager\fP & \fBoperator=\fP (\fBInputManager\fP &&)=default"
.br
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.ti -1c
.RI "bool \fBis_key_pressed\fP (sf::Keyboard::Key key) const"
.br
.ti -1c
.RI "bool \fBis_mouse_button_pressed\fP (sf::Mouse::Button button) const"
.br
.ti -1c
.RI "sf::Vector2i \fBget_mouse_position\fP (const sf::Window &window) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
