.TH "rtype::TextureLibrary" 3 "Thu Jan 11 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rtype::TextureLibrary
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextureLibrary\fP (const \fBTextureLibrary\fP &)=default"
.br
.ti -1c
.RI "\fBTextureLibrary\fP (\fBTextureLibrary\fP &&)=default"
.br
.ti -1c
.RI "\fBTextureLibrary\fP & \fBoperator=\fP (const \fBTextureLibrary\fP &)=default"
.br
.ti -1c
.RI "\fBTextureLibrary\fP & \fBoperator=\fP (\fBTextureLibrary\fP &&)=default"
.br
.ti -1c
.RI "\fBTextureBook\fP & \fBget_texture\fP (std::string &name)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
