.TH "rtype::EntityManager::EntityException" 3 "Sat Jan 13 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rtype::EntityManager::EntityException
.SH SYNOPSIS
.br
.PP
.PP
Inherits std::exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEntityException\fP (std::string &&perror='Error')"
.br
.ti -1c
.RI "\fBEntityException\fP (\fBEntityException\fP const &to_copy)=default"
.br
.ti -1c
.RI "\fBEntityException\fP (\fBEntityException\fP &&to_move)=default"
.br
.ti -1c
.RI "\fBEntityException\fP & \fBoperator=\fP (\fBEntityException\fP const &to_copy)=default"
.br
.ti -1c
.RI "\fBEntityException\fP & \fBoperator=\fP (\fBEntityException\fP &&to_move)=default"
.br
.ti -1c
.RI "const char * \fBwhat\fP () const noexcept override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
