.TH "rtype::utils::Colors" 3 "Fri Jan 12 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rtype::utils::Colors
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBred\fP {}"
.br
.ti -1c
.RI "unsigned char \fBgreen\fP {}"
.br
.ti -1c
.RI "unsigned char \fBblue\fP {}"
.br
.ti -1c
.RI "unsigned char \fBopacity\fP {}"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
