.TH "rtype::BGMManager" 3 "Mon Jan 8 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rtype::BGMManager
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBGMManager\fP (const \fBBGMManager\fP &)=delete"
.br
.ti -1c
.RI "\fBBGMManager\fP (\fBBGMManager\fP &&)=delete"
.br
.ti -1c
.RI "\fBBGMManager\fP & \fBoperator=\fP (const \fBBGMManager\fP &)=delete"
.br
.ti -1c
.RI "\fBBGMManager\fP & \fBoperator=\fP (\fBBGMManager\fP &&)=delete"
.br
.ti -1c
.RI "void \fBplay_music\fP (const std::string &name)"
.br
.ti -1c
.RI "void \fBset_volume\fP (float volume)"
.br
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
