.TH "rtype::utils::Vector2D< TComponent >" 3 "Sun Jan 14 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rtype::utils::Vector2D< TComponent > \- Structure for 2 values, x and y\&. Values can be anything, as long as its consistent\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Vector2D\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TComponent \fBx\fP {0}"
.br
.ti -1c
.RI "TComponent \fBy\fP {0}"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename TComponent>
.br
struct rtype::utils::Vector2D< TComponent >"
Structure for 2 values, x and y\&. Values can be anything, as long as its consistent\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fITComponent\fP - template value 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
