.TH "rtype::SpriteComponent" 3 "Wed Jan 10 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rtype::SpriteComponent
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBrtype::utils::TextureRect\fP \fBrectangle\fP {}"
.br
.ti -1c
.RI "std::string \fBtexture_path\fP {}"
.br
.ti -1c
.RI "\fBrtype::utils::Vector2D\fP< float > \fBorigin\fP {}"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
