.TH "rtype::utils" 3 "Sun Jan 14 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rtype::utils \- define enums of basic colors to not be obligated to define them each time Should be noted that it does not seems to works on windows  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBClock\fP"
.br
.RI "Class to keep track of time\&. Can be reset, and can get time in seconds or miliseconds\&. "
.ti -1c
.RI "class \fBColors\fP"
.br
.RI "\fBColors\fP class\&. "
.ti -1c
.RI "class \fBThreadPool\fP"
.br
.RI "Handle threads\&. The program has different parts of the code launched in different threads, to optimize run-time\&. "
.ti -1c
.RI "struct \fBVector2D\fP"
.br
.RI "Structure for 2 values, x and y\&. Values can be anything, as long as its consistent\&. "
.ti -1c
.RI "class \fBTextureRect\fP"
.br
.RI "x, y, width and height values to have a rect\&. Is used for texture, hence its name "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr int \fBMAX_COLOR\fP {255}"
.br
.in -1c
.SH "Detailed Description"
.PP 
define enums of basic colors to not be obligated to define them each time Should be noted that it does not seems to works on windows 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
