.TH "rtype::SFXManager" 3 "Thu Jan 11 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rtype::SFXManager
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSFXManager\fP (const \fBSFXManager\fP &)=default"
.br
.ti -1c
.RI "\fBSFXManager\fP (\fBSFXManager\fP &&)=default"
.br
.ti -1c
.RI "\fBSFXManager\fP & \fBoperator=\fP (const \fBSFXManager\fP &)=default"
.br
.ti -1c
.RI "\fBSFXManager\fP & \fBoperator=\fP (\fBSFXManager\fP &&)=default"
.br
.ti -1c
.RI "void \fBplay_sound\fP (const std::string &name)"
.br
.ti -1c
.RI "void \fBset_volume\fP (float volume)"
.br
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
