.TH "rtype::SFMLKeyring" 3 "Mon Jan 8 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rtype::SFMLKeyring
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "sf::Keyboard::Key \fBsfml_key\fP"
.br
.ti -1c
.RI "rtype::Keys \fBkey\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
