.TH "rtype::TransformComponent" 3 "Sat Jan 13 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rtype::TransformComponent
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransformComponent\fP (float position_x=0, float position_y=0, float velocity_x=0, float velocity_y=0, float scale_x=1, float scale_y=1)"
.br
.ti -1c
.RI "\fBTransformComponent\fP (const \fBTransformComponent\fP &transform)=default"
.br
.ti -1c
.RI "\fBTransformComponent\fP (\fBTransformComponent\fP &&transform)=default"
.br
.ti -1c
.RI "\fBTransformComponent\fP & \fBoperator=\fP (const \fBTransformComponent\fP &transform)=default"
.br
.ti -1c
.RI "\fBTransformComponent\fP & \fBoperator=\fP (\fBTransformComponent\fP &&transform)=default"
.br
.ti -1c
.RI "\fBTransformComponent\fP & \fBoperator=\fP (const nlohmann::json &json)"
.br
.ti -1c
.RI "\fBTransformComponent\fP (const nlohmann::json &json)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBposition_x\fP {0}"
.br
.ti -1c
.RI "float \fBposition_y\fP {0}"
.br
.ti -1c
.RI "float \fBvelocity_x\fP {0}"
.br
.ti -1c
.RI "float \fBvelocity_y\fP {0}"
.br
.ti -1c
.RI "float \fBscale_x\fP {1}"
.br
.ti -1c
.RI "float \fBscale_y\fP {1}"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
