.TH "rtype::SFMLAudioModule" 3 "Tue Jan 9 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rtype::SFMLAudioModule
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBrtype::IAudioModule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSFMLAudioModule\fP (const \fBSFMLAudioModule\fP &)=delete"
.br
.ti -1c
.RI "\fBSFMLAudioModule\fP (\fBSFMLAudioModule\fP &&)=delete"
.br
.ti -1c
.RI "\fBSFMLAudioModule\fP & \fBoperator=\fP (const \fBSFMLAudioModule\fP &)=delete"
.br
.ti -1c
.RI "\fBSFMLAudioModule\fP & \fBoperator=\fP (\fBSFMLAudioModule\fP &&)=delete"
.br
.ti -1c
.RI "void \fBplay_music\fP (const std::string &name) final"
.br
.ti -1c
.RI "void \fBplay_sfx\fP (const std::string &name) final"
.br
.ti -1c
.RI "void \fBset_volume_music\fP (float volume) final"
.br
.ti -1c
.RI "void \fBset_volume_sfx\fP (float volume) final"
.br
.ti -1c
.RI "void \fBupdate\fP () final"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
