.TH "rtype::TextComponent" 3 "Thu Jan 11 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rtype::TextComponent
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBrtype::utils::Colors\fP \fBcolors\fP {}"
.br
.ti -1c
.RI "unsigned int \fBopacity\fP {}"
.br
.ti -1c
.RI "unsigned int \fBfont_size\fP {}"
.br
.ti -1c
.RI "std::string \fBtext\fP {}"
.br
.ti -1c
.RI "std::string \fBfont_path\fP {}"
.br
.ti -1c
.RI "\fBrtype::utils::Vector2D\fP< float > \fBorigin\fP {}"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
