.TH "rtype::ISparseArray" 3 "Fri Jan 12 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rtype::ISparseArray
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBrtype::SparseArray< TComponent >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBISparseArray\fP (\fBISparseArray\fP const &to_copy)=default"
.br
.ti -1c
.RI "\fBISparseArray\fP (\fBISparseArray\fP &&to_move)=default"
.br
.ti -1c
.RI "\fBISparseArray\fP & \fBoperator=\fP (\fBISparseArray\fP const &to_copy)=default"
.br
.ti -1c
.RI "\fBISparseArray\fP & \fBoperator=\fP (\fBISparseArray\fP &&to_move)=default"
.br
.ti -1c
.RI "virtual void \fBremove\fP (size_t entity)=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
