.TH "rtype::SystemManager" 3 "Wed Jan 10 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rtype::SystemManager
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSystemManager\fP (\fBSystemManager\fP const &to_copy)=default"
.br
.ti -1c
.RI "\fBSystemManager\fP (\fBSystemManager\fP &&to_move)=default"
.br
.ti -1c
.RI "\fBSystemManager\fP & \fBoperator=\fP (\fBSystemManager\fP const &to_copy)=default"
.br
.ti -1c
.RI "\fBSystemManager\fP & \fBoperator=\fP (\fBSystemManager\fP &&to_move)=default"
.br
.ti -1c
.RI "std::function< void(\fBComponentManager\fP &, float)> & \fBadd_system\fP (std::function< void(\fBComponentManager\fP &, float)> &function)"
.br
.ti -1c
.RI "void \fBupdate\fP (\fBComponentManager\fP &registry, float delta_time)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
