.TH "rtype::AnimationClip" 3 "Thu Jan 11 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rtype::AnimationClip
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBanimation_name\fP"
.br
.ti -1c
.RI "bool \fBis_loop\fP {false}"
.br
.ti -1c
.RI "double \fBtime_after_change\fP"
.br
.ti -1c
.RI "std::vector< \fBrtype::utils::TextureRect\fP > \fBtexture_rects\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
