.TH "rtype::utils::Colors" 3 "Thu Jan 11 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rtype::utils::Colors
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBred\fP {0}"
.br
.ti -1c
.RI "unsigned char \fBgreen\fP {0}"
.br
.ti -1c
.RI "unsigned char \fBblue\fP {0}"
.br
.ti -1c
.RI "unsigned char \fBopacity\fP {MAX_COLOR}"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const \fBColors\fP \fBBlack\fP {0, 0, 0}"
.br
.ti -1c
.RI "static const \fBColors\fP \fBWhite\fP {255, 255, 255}"
.br
.ti -1c
.RI "static const \fBColors\fP \fBRed\fP {255, 0, 0}"
.br
.ti -1c
.RI "static const \fBColors\fP \fBGreen\fP {0, 0, 255}"
.br
.ti -1c
.RI "static const \fBColors\fP \fBBlue\fP {0, 0, 255}"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
