.TH "rtype::utils::TextureRect" 3 "Thu Jan 11 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rtype::utils::TextureRect
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextureRect\fP (int p_x=0, int p_y=0, int pwidth=0, int pheight=0)"
.br
.ti -1c
.RI "\fBTextureRect\fP (const \fBTextureRect\fP &to_copy)=default"
.br
.ti -1c
.RI "\fBTextureRect\fP (\fBTextureRect\fP &&to_move)=default"
.br
.ti -1c
.RI "\fBTextureRect\fP & \fBoperator=\fP (const \fBTextureRect\fP &to_copy)=default"
.br
.ti -1c
.RI "\fBTextureRect\fP & \fBoperator=\fP (\fBTextureRect\fP &&to_move)=default"
.br
.ti -1c
.RI "\fBTextureRect\fP (const nlohmann::json &json)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP {0}"
.br
.ti -1c
.RI "int \fBy\fP {0}"
.br
.ti -1c
.RI "int \fBwidth\fP {0}"
.br
.ti -1c
.RI "int \fBheight\fP {0}"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
