.TH "rtype::utils::TextureRect" 3 "Tue Jan 9 2024" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rtype::utils::TextureRect
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP {0}"
.br
.ti -1c
.RI "int \fBy\fP {0}"
.br
.ti -1c
.RI "int \fBwidth\fP {0}"
.br
.ti -1c
.RI "int \fBheight\fP {0}"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
